config/routes.rb
Blog::Application.routes.draw do

get  "pages/eventv"
  get "pages/home"

  get "pages/contact"

  get "pages/about"

  get "pages/help"

  get "about/index"

  get "home/index"

  get "pages/newevent"

resources :users do
    member do
        get :doing_tasks, :following 
    end
end

resources :sessions, :only => [:new, :create, :destroy]
resources :events, :only => [:new, :create, :destroy, :show] 
resources :follows, :only => [:create, :destroy]
resources :invites, :only =>[:new, :create, :destroy]
resources :takens, :only => [:create, :destroy]

resources :tasks, :only => [:create, :destroy, :new, :show] do
  member do
    post :taken
  end
end

match '/signup',:to => 'users#new'
match '/signin', :to => 'sessions#new'
match '/signout', :to => 'sessions#destroy'

root :to => 'pages#home'
match '/contact', :to => 'pages#contact'
match '/about',:to => 'pages#about'
match '/help',:to => 'pages#help'
match '/eventv',:to => 'pages#eventv'

match '/vanity(/:action(/:id(.:format)))', :controller=>:vanity

end

app/models/event.rb
class Event < ActiveRecord::Base
	  attr_accessible :date, :description, :title, :user_id

	  has_many :users
	  
	  
	  has_many :reverse_follows, :foreign_key=> "followed_id",
                                   :class_name => "Follow",
                                   :dependent => :destroy
	has_many :followers, :through => :reverse_follows, :source => :follower

	 has_many :reverse_invites, :foreign_key=> "eid",
                                   :class_name => "Invite",
                                   :dependent => :destroy
 has_many :inviters, :through => :reverse_relationships, :source => :inviter


	has_many :tasks, :dependent => :destroy
	belongs_to :user

	validates :description, :presence => true, :length => { :maximum => 400 }
	validates :user_id, :presence => true
	default_scope :order =>	 'events.created_at DESC'

	validates :title, :presence => true

	validates :date, :presence => true

	def following?(followed)
		follows.find_by_followed_id(followed)
	end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
before_filter :authenticate, :only => [:create, :show, :destroy]
#before_filter :creator_user, :only => :destroy


def new
	@event = Event.new
end

def create
@event = current_user.events.build(params[:event])

	if @event.save
		#flash[:success] = "Event created!"
		redirect_to event_path(@event)
		@current_user.followevent!(@event)
	else
		#flash[:error] = "Failed to create"
		render new_event_path
	end
end

def destroy
	@event = Event.find(params[:id])
	if @event.present?
	@event.destroy
	end
	redirect_back_or root_path
end


def followshow
end

def show
	#flash[:success] = "Event "
	@event = Event.find(params[:id])
	@events = @user.events

	#@events = @user.events.paginate(:page => params[:page])
	@title = @user.name
end


private

def authorized_user
	@event = Event.find(params[:id])
	redirect_to root_path unless current_user?(@event.user)
end


end

app/views/events/_event.html.erb
<% index |= 1 %>
<div > 
		<h4 style="display:inline;cursor:pointer;" id="event<%=index%>"> <%= event.title %>  <i class=" icon-arrow-down"> </i> </h4> 

		<small> by <% user = event.user rescue User.find(event.user_id) %> <%= user.name%> </small>

		<br>
		<div class="description"> <p style="display:inline"><%= event.description %> <br> </div>
   		<!-- <i class="icon-globe"> </i>  -->On <%= time_tag(event.date) %> 
   		<!-- <i class="icon-star"> </i>  --> <small> and has </small> <%= pluralize(event.tasks.count,"task") %><br>

   		<% homeevent = Event.find_by_id(event.id)%>
   				
   				<% if current_user.following?(homeevent)%>
		<i class="icon-plus-sign"> </i>	<%= link_to " Task ", new_task_path(:id => event.id), :class=> "mylink"%>  
		<% end %>

			
		   <% if current_user?(user) %>
		 	<i class="icon-trash"> </i> <%= link_to "  Delete", event, :method => :delete, :confirm => "You sure?", :title => event.title, :class => "mylink" %>
			   	 <%#= link_to "Invite People",new_invite_path(:id =>event.id), :class => "btn"%>   	 
			<% end %>
			<i class="icon-time"> </i> <small style="display:inline"> <%= time_ago_in_words(event.created_at) %> ago. </small>

			 <%= render :partial => 'users/follow_form',:locals => { :event => event} if signed_in? %>


		</p>
 </div> 


		<% unless event.tasks.empty? %>			
		<div class="task_list"id="tasks<%= index %>">

				<% event.tasks.each_with_index do |task, index| %>
					

				<h5 style="display:inline"> <%= task.title %> : </h5> 
				
				<small> by <% user = task.user rescue User.find(task.user_id)%> <%= user.name%> </small>

   			 	<div class="description"> <p style="display:inline"> <%= task.description %> <br> </div>
   			 	<i class="icon-user"> </i> <%= task.required - task.users.count%>  Required &nbsp
   			 	<i class="icon-globe"> </i> On <%= time_tag(task.date) %> 
						
  
   				<% homeevent = Event.find_by_id(task.event_id)%>
   				<% creator_user = User.find(homeevent.user_id)%>
   				<% if current_user?(user) || current_user?(creator_user)%>
	   				<i class="icon-trash"> </i> 
	   				<%= link_to "Delete", task, :method => :delete, :confirm => "You sure?",    :title => task.title%> &nbsp
   				<% end %>
   				<!-- <i class="icon-time"> </i> <small> <%= time_ago_in_words(event.created_at) %> ago. </small> -->

   				 <%= render :partial => 'users/doform',:locals => { :task => task}  if signed_in? %>
   				</p>
   				
   				<% end %>

   		</div>
	
		

			<%end%>
			<hr>

app/views/events/index.html.erb
<h1>All events</h1>
<% render @events %>

app/views/events/new.html.erb
<h1>Create Events</h1>
<%= render 'shared/event_form' %>

app/views/events/show.html.erb
<h3> You are following <%= pluralize(current_user.follows.count, "event")%>
						 and have signed up for <%= pluralize(current_user.doing_tasks.count,"task") %></h3>
				
				<h4> <i class="icon-pencil"> </i> <%= link_to 'Create Event', new_event_path %> &nbsp
					<i class = "icon-list"> </i> <%= link_to 'All Events', root_path%>
				</h4>

				<hr class="main_line">
	<h4> You are viewing Event <%=@event.title %></h4>
<%= render @event %>