config/routes.rb
Blog::Application.routes.draw do

get  "pages/eventv"
  get "pages/home"

  get "pages/contact"

  get "pages/about"

  get "pages/help"

  get "about/index"

  get "home/index"

  get "pages/newevent"

resources :users do
    member do
        get :doing_tasks, :following 
    end
end

resources :sessions, :only => [:new, :create, :destroy]
resources :events, :only => [:new, :create, :destroy, :show] 
resources :follows, :only => [:create, :destroy]
resources :invites, :only =>[:new, :create, :destroy]
resources :takens, :only => [:create, :destroy]

resources :tasks, :only => [:create, :destroy, :new, :show] do
  member do
    post :taken
  end
end

match '/signup',:to => 'users#new'
match '/signin', :to => 'sessions#new'
match '/signout', :to => 'sessions#destroy'

root :to => 'pages#home'
match '/contact', :to => 'pages#contact'
match '/about',:to => 'pages#about'
match '/help',:to => 'pages#help'
match '/eventv',:to => 'pages#eventv'

match '/vanity(/:action(/:id(.:format)))', :controller=>:vanity

end

app/models/event.rb
class Event < ActiveRecord::Base
	  attr_accessible :date, :description, :title, :user_id

	  has_many :users
	  
	  
	  has_many :reverse_follows, :foreign_key=> "followed_id",
                                   :class_name => "Follow",
                                   :dependent => :destroy
	has_many :followers, :through => :reverse_follows, :source => :follower

	 has_many :reverse_invites, :foreign_key=> "eid",
                                   :class_name => "Invite",
                                   :dependent => :destroy
 has_many :inviters, :through => :reverse_relationships, :source => :inviter


	has_many :tasks, :dependent => :destroy
	belongs_to :user

	validates :description, :presence => true, :length => { :maximum => 400 }
	validates :user_id, :presence => true
	default_scope :order =>	 'events.created_at DESC'

	validates :title, :presence => true

	validates :date, :presence => true

	def following?(followed)
		follows.find_by_followed_id(followed)
	end
end

app/models/follow.rb
class Follow < ActiveRecord::Base
	attr_accessible :followed_id ,:follower_id
	belongs_to :follower, :class_name => "User"
	belongs_to :followed, :class_name => "Event"

	validates :follower_id, :presence => true
	validates :followed_id, :presence => true
end

app/models/invite.rb
class Invite < ActiveRecord::Base
  attr_accessible :uid, :eid

  belongs_to :inviter, :class_name => "User"
belongs_to :invitee, :class_name => "User"

validates :uid, :presence => true
validates :eid, :presence => true


end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :name, :title
  validates :name,	:presence =>true
  validates :title,	:presence =>true,
			:length => { :minimum => 5 }


end

app/models/taken.rb
class Taken < ActiveRecord::Base
  attr_accessible :taken_id
  
  belongs_to :taker, :class_name => "User"
  belongs_to :taken, :class_name => "Task"

  validates :taken_id, :presence => true
  validates :taken_id, :presence => true

end

app/models/task.rb
  class Task < ActiveRecord::Base
  attr_accessible :date, :description, :event_id, :required, :title, :user_id, :signedup

  belongs_to :event #:dependent => :destroy
  has_many :users, :through => :takens, :source => :taker

  has_many :takens, :foreign_key => "taken_id",
					:dependent => :destroy

  
  default_scope :order => 'tasks.created_at DESC'

  validates :title, :presence =>true, :length => { :maximum => 40}
  validates :description, :presence => true, :length => { :maximum => 140}

  validates :user_id, :presence =>true
  validates :event_id, :presence =>true

  validates :required, :presence =>true
  validates :signedup, :presence =>true

  def taken?(followed)
    takens.find_by_taken_id(taken)
  end

end

app/models/user.rb
require 'digest'

class User < ActiveRecord::Base
attr_accessor :password
attr_accessible :name, :email, :password, :password_confirmation
has_many :events, :dependent => :destroy
has_many :tasks, :dependent => :destroy
has_many :follows, :foreign_key => "follower_id", :dependent => :destroy
has_many :invites, :foreign_key =>"uid"


has_many :takens, :foreign_key => "taker_id",
				  :dependent => :destroy

has_many :doing_tasks, :through => :takens, :source => :taken
# has_many  :doing_tasks, :through => :takens, :source => :taken

email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, :presence => true,
  				   :length   => { :maximum => 50}
  validates :email, :presence =>true
  validates :email, :presence => true,
					:format       => { :with => email_regex },
					:uniqueness	 => { :case_sensitive => false }
validates :password, :presence => true,
						:confirmation => true,
						:length  => { :within => 6..40 }

validates :password_confirmation, :presence => true

before_save :encrypt_password

# Return true if the user's password matches the submitted password.
def has_password?(submitted_password)
	encrypted_password == encrypt(submitted_password)
end
def following?(followed)
	follows.find_by_followed_id(followed)
end

def followevent!(followed) 
	follows.create!(:followed_id => followed.id)
end

def unfollow!(followed)
	follows.find_by_followed_id(followed).destroy
end

def followfind(follower)
	return follows.find_by_followed_id(follower)

end

def invitesend(eve)
	invites.create(:eid => :eve.id)
end

def uninvite!(followed)
	invites.find_by_invite_id(followed).destroy
end

def taken?(task)

	self.takens.where("taken_id = ?",task.id).present?

end

def take!(taken)

	takens.create!(:taken_id => taken.id)

end

def leave_task!(taken)
	self.takens.find_by_id(taken).destroy
	
end

	#def feed
# This is preliminary. See Chapter 12 for the full implementation.
#Micropost.where("user_id = ?", id)
#end
private
	def encrypt_password
		self.salt = make_salt if new_record?
		self.encrypted_password = encrypt(password)
	end
	def encrypt(string)
		secure_hash("#{salt}--#{string}")
	end
	def make_salt
		secure_hash("#{Time.now.utc}--#{password}")
	end
	def secure_hash(string)
		Digest::SHA2.hexdigest(string)
	end




def self.authenticate(email, submitted_password)
user = find_by_email(email)
return nil if user.nil?
return user if user.has_password?(submitted_password)
end

def self.authenticate_with_salt(id)#, cookie_salt)
user = find_by_id(id) 
return user
#(user && user.salt == cookie_salt) ? user : nil
end



end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  @time =Time.now

  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/task_controller.rb
class TaskController < ApplicationController

#before_filter signed_in?   && belongs_to_event??
	def new
		@task = Task.new
		render 'task/new'
	end
	
	def create
		@task = current_event.task.build(params[:task])
		@task.user_id = current_user.id
		if @task.save
			flash[:success] = "New Task Created"
		else
			render 'pages/home'
		end
	end

	def destroy   #should check if the current_user is same as creator user_id
		@task = Task.find(params[:id])
    	@task.destroy
	end

	def show

	end

end

app/controllers/temp_controller.rb
class TempController < ApplicationController
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    cookies.permanent.signed[:remember_token] = [user.id]#, user.salt]
    self.current_user = user
  end
  
  def current_user=(user)
    @current_user = user
  end
  
  def current_user
    @current_user ||= user_from_remember_token
  end
  
  def signed_in?
    !current_user.nil?
  end
  
  def sign_out
    cookies.delete(:remember_token)
    self.current_user = nil
  end

def current_user?(user)
user == current_user
end
def authenticate
deny_access unless signed_in?
end
def deny_access
store_location
redirect_to signin_path, :notice => "Please sign in to access this page."
end

def redirect_back_or(default)
redirect_to(session[:return_to] || default)
clear_return_to
end


  
  private
  
    def user_from_remember_token
      User.authenticate_with_salt(*remember_token)
    end
    
    def remember_token
      cookies.signed[:remember_token] || [nil]#, nil]
    end
    def store_location
		session[:return_to] = request.fullpath
	end
	def clear_return_to
	session[:return_to] = nil
	end


end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/temp_helper.rb
module TempHelper
end

app/helpers/users_helper.rb
module UsersHelper
def gravatar_for(user, options = { :size => 50 })
gravatar_image_tag(user.email.downcase, :alt => user.name,
:class => 'gravatar',
:gravatar => options)
end
end

app/views/layouts/_footer.html.erb
<div class="navbar-fixed-bottom">
	<div class="navbar-inner">
		    <ul class="nav nav-pills pull-right">
		      <li><%= link_to "About",   about_path %></li>
		      <li><%= link_to "Help", help_path %></li>
		      <li><%= link_to "Contact", contact_path %></li>
		      <!-- <li><a href="http:///">News</a></li> -->
		    </ul>
		
	</div>
</div>

app/views/layouts/_header.html.erb
<div class="container">
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
  	<div class="nav nav-pills pull-right">
    
			<!-- <ul class> -->
				<div class="brand">
					<li> <%= link_to "MI-Teamer", root_path %></li>
				</div>
				<% if signed_in? %>
					<li><%= link_to "Events", current_user %></li>
					<li><%= link_to "Tasks", task_path(current_user) %> </li>
					<li><%= link_to "Settings", edit_user_path(current_user) %></li>
				<% end %>
				
				<% if signed_in? %>
					<!-- <li><%= link_to "Users", users_path %></li> -->
					<li><%= link_to "Sign Out", signout_path, :method => :delete %></li>
				<% else %>
					<li> <%= link_to "Sign Up", signup_path%></li>
					<li><%= link_to "Sign In", signin_path %></li>
				<% end %>
			<!-- </ul> -->
		</div>
	</div>
</div>
</div>

app/views/layouts/_sidebar.html.erb
<h2> <%= current_user.name%>  </h2>
<h5>
	<%= link_to user_path(current_user), current_user %>  <br>
	Signedup <%= pluralize(current_user.events.count, "event") %> <br>
</h5>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Teamer</title>
<%= csrf_meta_tag %>

<%= javascript_include_tag "application" %>
<%= stylesheet_link_tag 'bootstrap.css' %>
<%= stylesheet_link_tag 'bootstrap.min.css'%>
<%= stylesheet_link_tag 'bootstrap-responsive.min.css'%>
<%= stylesheet_link_tag 'custom.css'%>



</head>
<body>


<%= render 'layouts/header' %>

<div class="container">


	

	<section>
		<div  class="alert-message">
			<% flash.each do |key, value| %>
				<div class="flash" <%= key %>  > <%= value %></div>
			<% end %>
		

	<div>

		<%= yield %>
	</section>


	<%= render 'layouts/footer' %>

</div>

</body>
</html>

app/views/pages/about.html.erb
<h1>About Teamer</h1>
<p>
	Teamer is a easy to use interface that helps connect people part of a organisaion or a team. It makes easy co-ordination of various members in to easy manageable events and tasks.

	Teamer is born out of the need for an online application that could cater to the needs of student bodies in Universities. But soon, it has grown in to an application that every organisation must have.

</p>

<p>
	This is made by interns <a href="http://www.facebook.com/amrit.sahoo"> Amrit Sahoo </a> and <a href="http://www.facebook.com/vishnu.vinjam"> Vishnu Vinjam </a> of <a href="http://chronus.com"> Chronus Corporation</a> on <a href="http://rubyonrails.org/"> Ruby on Rails </a>

</p>

app/views/pages/contact.html.erb
<div class="masthead">
	<h1>Teamer</h1>
</div>
<br>
<p style="font-size:30px ; display:inline">
	Made possible at <a href="http://chronus.com/"> Chronus Corporation </a> </p>
<p style="font-size:17px"> by Amrit Sahoo and Vishnu Vinjam </p>
	Find us at 'amrit.sahoo@chronus.com' and 'vishnu.vinjam@chronus.com'

</p>

app/views/pages/help.html.erb
<h1>Instructions</h1>
<p>
Click on 'Join' to signup Teamer <br>
</p>

app/views/pages/home.html.erb
<% if signed_in? %>

		
	<div class="span12">		
		<div class="span9">

			<h2 style="display:inline"> Welcome <%= current_user.name%></h2><br>
			<p> Checkout various events you want to contribute in.</p>
			
			<h4> 
				<i class = "icon-list"> </i> <%= link_to 'Your Events', user_path(current_user)%> &nbsp
				<i class= "icon-ok">  </i><%= link_to ' Your Tasks', task_path(@current_user)%>
				<span class="pull-right">
					<i class="icon-pencil"> </i> <%= link_to 'Create Event', new_event_path %>
				</span>
			</h4>
				
			<hr>

				<%#= render 'shared/user_info' %>
								
				<%  @eventlist=Event.all %>
					<% # @eventlist= @eventlist.paginate(:page => 1, :per_page => 2)%>
				<% @eventlist.each_with_index do |vel,index|%>
					<div>
					<table class="table table-striped">
						<%= render vel, :index => index %>
					</table>
					<%#= will_paginate @listss %>
					</div>
				<% end %>


					</div>
				
<!-- <div class="nav nav-tabs nav-stacked" >
	<%# render 'layouts/sidebar'%>
</div>
 -->

 				<br>
<br>
<br>

			</div>

	<%# fadsfds%>


<% else %>
	<div style="text-align:center;background:url(http://www.wespeaknews.com/wp-content/uploads/2011/12/mood-indigo-2011.jpg);">
		<div class="masthead">
			<h1 style="font-size:70px;color:#fff;"><i>MI</i> Teamer</h1>
			<hr >
			<p style="color:#fff;">
				&nbsp; Teamer provides a simple interface to create, join and invite to events. 
				
				It helps you to team up and collaborate effortlessly to make ideas happen.
				Organisations, non-profits and infomal groups can now work seamlessly towards their goals.
			</p>

			<h2 style ="font-size:40px; color:#fff;">Get started for only $<%= ab_test :price_options %> a month!</h2>
			
		</div>
		<br>
		<div class="btn btn-success btn-small" style="text-align:center;"> 
			
			
			<%= link_to "Join now!", signup_path, :class => (ab_test :signup_link)  %> <!-- , style: bigger %>  -->
			
		</div>
		<br><br><br>
	</div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
<div id="error_explanation">
<h2><%= pluralize(object.errors.count, "error") %>
prohibited this user from being saved:</h2>
<p>There were problems with the following fields:</p>
<ul>
<% object.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
</div>
<% end %>

app/views/shared/_event_form.html.erb
<%= simple_form_for @event do |f| %>

  <%= f.input :title%>
  <%= f.input :description%>
  *Date <br>
  
<div id="datetimepicker1" class="input-append date">
  <%= f.text_field :date,:required => true %>
    <span class="add-on">
      <i data-time-icon="icon-time" data-date-icon="icon-calendar">
        </i>
      </span>
    
  </div><br ><br >
  <%= f.submit 'Create', :class => "btn btn-primary"%>

<% end %>

<!--
<%= form_for @event do |f| %>
<%= render 'shared/error_messages', :object => f.object %>
 
	<%= f.label :title%>
	<%= f.text_field :title %>
  <br>
  Date and Time <br>
  <%= f.datetime_picker 'date', :dateFormat => "yy-mm-dd " , :timeFormat=> "hh:mm tt z" %>

<div class="field">
	<%= f.label :description%>
	<%= f.text_area :description %>

</div>

<div class="actions">
	<%= f.submit "Submit" %>
</div>
<% end %>
-->

app/views/shared/_feed.html.erb
<% unless @feed_items.empty? %>
<table class="microposts" summary="User microposts">
<%= render :partial => 'shared/feed_item', :collection => @feed_items %>
</table>
<%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<tr>
<td class="gravatar">
<%= link_to gravatar_for(feed_item.user), feed_item.user %>
</td>
<td class="micropost">
<span class="user">
<%= link_to feed_item.user.name, feed_item.user %>
</span>
<span class="content"><%= feed_item.content %></span>
<span class="timestamp">
Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
</span>
</td>
<% if current_user?(feed_item.user) %>
<td>
<%= link_to "delete", feed_item, :method => :delete,
:confirm => "You sure?",
:title => feed_item.content %>
</td>
<% end %>
</tr>

app/views/shared/_task_form.html.erb
	<%= simple_form_for @task do |f| %>
  <%= f.input :title%>
  <%= f.input :description%>
  *Date <br>
  <%#= f.datetime_picker :date, :dateFormat => "yy-mm-dd " , :timeFormat=> "hh:mm tt z" %> 
  <div id="datetimepicker1" class="input-append date">
  <%= f.text_field :date ,:required => true %>
    <span class="add-on">
      <i data-time-icon="icon-time" data-date-icon="icon-calendar">
        </i>
      </span>
    
  </div><br ><br >


  <%= f.input :required, :label => "Required Members" %>

	<%= f.hidden_field :event_id, :value => @event.id %>
	<%= f.hidden_field :signedup, :value => 0 %>


  <%= f.submit 'Create', :class => "btn btn-primary"%>
<% end %>

<!--
<%= form_for @task do |f| %>

	<%= render 'shared/error_messages', :object => f.object %>
	<div class="title">
		<%= f.label :title%>
	<%= f.text_field :title %>
	</div>

	<div class="field">
	<%= f.label :description%>
	<%= f.text_area :description %>

	</div>

	Date and Time <br>
	<%= f.datetime_picker 'date', :dateFormat => "yy-mm-dd " , :timeFormat=> "hh:mm tt z" %>
	<br>

	<%= f.label :required%>
	<%= f.text_field :required %>
	<br>


	<%= f.hidden_field :event_id, :value => @event.id %>
	<%= f.hidden_field :signedup, :value => 0 %>

	<div class="actions">
	<%= f.submit "Create task" %>
	</div>
<% end %>
-->

app/views/shared/_user_info.html.erb
<h2> <%= current_user.name%>  </h2>
<h5>
	<a href="<%= user_path(current_user) %>">
	<%= gravatar_for current_user, :size => 30 %> <br>
</a>
	Signedup <%= pluralize(current_user.events.count, "event") %> <br>
	Doing <%= pluralize( current_user.doing_tasks.count, "task") %> <br> 
	
</h5>